### PR TITLE
Update addEventListener to match new API from PR #36

### PR DESCRIPTION
**Pull request by HParker**
This updates the documentation for event listeners to match the new `call` and pass a `Proc` syntax.

### CODE REVIEW

**Review by kateinoigakukun — CHANGES_REQUESTED** [review]
The API is not new. Why you prefer the proc one?

**Comment by HParker** [comment]
Sorry, maybe this is my mistake/misunderstanding. The example in `lucky.html` doesn't work for me.

I get the error,

```
Unhandled Promise Rejection: Error: eval:3:in `<main>': undefined method `addEventListner' for [object HTMLDocument]:JS::Object 
```

From this test case,

```html
  <script src="https://cdn.jsdelivr.net/npm/ruby-head-wasm-wasi@latest/dist/browser.umd.js"></script>
  <script>
    const { DefaultRubyVM } = window["ruby-wasm-wasi"];
    const main = async () => {
      // Fetch and instantiate WebAssembly binary
      const response = await fetch(
        //      Tips: Replace the binary with debug info if you want symbolicated stack trace.
        //      (only nightly release for now)
        //      "https://cdn.jsdelivr.net/npm/ruby-head-wasm-wasi@next/dist/ruby.debug+stdlib.wasm"
        "https://cdn.jsdelivr.net/npm/ruby-head-wasm-wasi@latest/dist/ruby.wasm"
      );
      const buffer = await response.arrayBuffer();
      const module = await WebAssembly.compile(buffer);
      const { vm } = await DefaultRubyVM(module);

      vm.printVersion();
      vm.eval(`
       require "js"
       JS.global[:document].addEventListener("click") do |event|
         p event
       end`);
    };

    main();
  </script>
  <body></body>
</html>
```

Because if this I assumed that the `addEventListener` had been deprecated.

Note: it fails with and without the typo in the `lucky.html` example.

**Comment by kateinoigakukun** [comment]
@HParker The error is raised expectedly because `document` does not have `addEventListener` method.
I think `lucky.html` works well but the codeb example you edited doesn't because of misuse of Web API. You you update the line with `JS.global[:document].getElementById("button").addEventListener "click" do` ?

**Comment by HParker** [comment]
First error I get with that is,

```
undefined method `getElementById' for [object HTMLDocument]:JS::Object 
```

If I change it to,

```ruby
JS.global[:document].call(:getElementById, "hi").addEventListener "click" do |event|
  p event
end
```

I get,

```
undefined method `addEventListener' for [object HTMLButtonElement]:JS::Object (NoMethodError)
```

If I change that to,

```ruby
JS.global[:document].call(:getElementById, "hi").call :addEventListener, "click", ->(event) do
  p event
end
```

I get no errors

**Comment by HParker** [comment]
Maybe it is because the `method_missing` is defined in `JS::JS::Object` by accident?

**Comment by HParker** [comment]
Maybe something is going wrong with the `method_missing` on `JS::Object`. I'll try to build from source and see if I can figure out what is going on.

**Comment by HParker** [comment]
Thank you!

Fetching `"https://cdn.jsdelivr.net/npm/ruby-head-wasm-wasi@next/dist/ruby.debug+stdlib.wasm"` resolves my issue 🤦 . I should have tried that first!

Thanks so much!

**Pull request closed without merging**
